const fs = require('fs');
const path = require('path');
const https = require('https');

/**
 * GitHub Pages Auto-Deploy Module
 * Pushes the generated landing page to a GitHub Pages repo via the GitHub API.
 * No npm packages needed — uses Node's built-in https module.
 */
class GitHubDeployer {
    constructor() {
        this.token = process.env.GITHUB_TOKEN;
        this.username = process.env.GITHUB_USERNAME;
        this.repo = process.env.GITHUB_REPO || 'ai-growth-os';
        this.branch = 'main';
    }

    _request(method, endpoint, body = null) {
        return new Promise((resolve, reject) => {
            const options = {
                hostname: 'api.github.com',
                path: endpoint,
                method,
                headers: {
                    'Authorization': `Bearer ${this.token}`,
                    'Accept': 'application/vnd.github+json',
                    'User-Agent': 'AI-Growth-Engine-OS',
                    'X-GitHub-Api-Version': '2022-11-28',
                    'Content-Type': 'application/json',
                },
            };

            const req = https.request(options, (res) => {
                let data = '';
                res.on('data', chunk => data += chunk);
                res.on('end', () => {
                    try {
                        resolve({ status: res.statusCode, body: JSON.parse(data) });
                    } catch {
                        resolve({ status: res.statusCode, body: data });
                    }
                });
            });

            req.on('error', reject);
            if (body) req.write(JSON.stringify(body));
            req.end();
        });
    }

    async _getFileSha(filePath) {
        const res = await this._request('GET', `/repos/${this.username}/${this.repo}/contents/${filePath}`);
        if (res.status === 200) return res.body.sha;
        return null;
    }

    async _pushFile(filePath, content, commitMessage) {
        const sha = await this._getFileSha(filePath);
        const encodedContent = Buffer.from(content).toString('base64');

        const body = {
            message: commitMessage,
            content: encodedContent,
            branch: this.branch,
        };
        if (sha) body.sha = sha; // Required for updates

        const res = await this._request('PUT', `/repos/${this.username}/${this.repo}/contents/${filePath}`, body);
        return res;
    }

    async ensureRepoExists() {
        const check = await this._request('GET', `/repos/${this.username}/${this.repo}`);
        if (check.status === 200) {
            console.log(`   ✅ Repo found: https://github.com/${this.username}/${this.repo}`);
            return true;
        }

        console.log(`   📦 Repo not found. Creating "${this.repo}"...`);
        const create = await this._request('POST', `/user/repos`, {
            name: this.repo,
            description: 'Auto-generated by AI Growth Engine OS',
            private: false,
            auto_init: true,
        });

        if (create.status === 201) {
            console.log(`   ✅ Repo created!`);
            // Wait a moment for GitHub to initialize the repo
            await new Promise(r => setTimeout(r, 3000));
            return true;
        }

        console.error(`   ❌ Failed to create repo:`, create.body.message);
        return false;
    }

    async enableGitHubPages() {
        const res = await this._request('POST', `/repos/${this.username}/${this.repo}/pages`, {
            source: { branch: this.branch, path: '/' },
        });
        // 201 = created, 409 = already exists (both are fine)
        return res.status === 201 || res.status === 409;
    }

    async deploy(htmlContent, dataJson) {
        if (!this.token || !this.username) {
            console.log(`   ⚠️ GITHUB_TOKEN or GITHUB_USERNAME not set in .env — skipping deploy.`);
            return null;
        }

        console.log(`   🔗 Connecting to GitHub...`);
        const repoReady = await this.ensureRepoExists();
        if (!repoReady) return null;

        const timestamp = new Date().toISOString();
        console.log(`   📤 Pushing landing page...`);
        await this._pushFile('index.html', htmlContent, `feat: AI auto-generated landing page [${timestamp}]`);

        console.log(`   📤 Pushing data snapshot...`);
        await this._pushFile('data.json', JSON.stringify(dataJson, null, 2), `data: update run snapshot [${timestamp}]`);

        console.log(`   🔧 Ensuring GitHub Pages is enabled...`);
        await this.enableGitHubPages();

        const liveUrl = `https://${this.username}.github.io/${this.repo}`;
        console.log(`   🌐 LIVE at: ${liveUrl}`);
        return liveUrl;
    }
}

module.exports = GitHubDeployer;
